#!/bin/bash

thor=$1

cat <<EOF
.. This file is autogenerated from THOR's --help detailed output. Do not edit.

.. highlight:: none

Command-Line Options
====================

This section lists the command-line options currently available in THOR.

EOF

$1 --help detailed 2>&1 | sed -E -f <(cat <<EOF
# Remove default values
s/\(default [^)]*\).*$//
s/\[=".*"\]/ /

# Indent options with short flag as expected by RST
s/^  -/      -/g

# Format section headers for RST
s/^> (.*) (-*)$/\1\n----------------------------------------------------------------------/g

# Format flags to have no indentation (so RST recognizes them)
s/^ {7}(-.*)$/\1/g

# Remove header text before Scan Options
0,/Scan Options/ {
        /Scan Options/ !d
}

# Remove Usage examples section
/Usage examples/,$ d

# Remove "Available modules:" line that is OS dependent
/Available modules: / d

# Separate line breaks in a flag description with an empty line, as expected by RST
s/^( {10,}[^- ].*)$/\n\1/g

# Turn "Warning:" pseudo-headers into RST warning directives
s/^(\s{10,})Warning: (.*)$/\1.. warning::\1   \2/g

# Render examples as literal blocks so backslashes and dashes are shown verbatim.
# Examples header; the examples follow on their own already-indented lines
s/^(\s{10,})(Examples):$/\1**\2**::\n/g
# Single example: Label and example on one line; the example has to be moved into a new block
s/^(\s{10,})(Example): (.*)$/\1**\2**::\n\1   \3/g

# Format "pseudo-headers" like "Alias:" in the flag description
s/^(\s{10,})([A-Z a-z]+:) (.*)$/\1\2\1  \3/g

# Remove trailing whitespace
s/ +$//g
EOF
)
